services:
  flask-app:
    image: python:3.9
    container_name: flask-app-jenkins
    ports:
      - "5001:5001"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root123
      - MYSQL_DB=blog
    volumes:
      - .:/app 
    command: >
      bash -c "
        apt update -y &&
        pip install --upgrade pip && 
        pip install --no-cache-dir -r requirements.txt &&
        python appWithDB-Auth-Swagger.py"
    working_dir: /app
    depends_on:
      - mysql
      - logstash

  mysql:
    image: mysql:8.0
    container_name: mysql-jenkins
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=blog
    volumes:
      - mysql-data:/var/lib/mysql
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch-jenkins
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
    volumes:
      - es_data:/usr/share/elasticsearch/data
  
  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.0
    container_name: logstash-jenkins
    ports:
      - "5044:5044" 
    environment:
      - "JVM_OPTS=-Xmx256m -Xms256m"
      - XPACK_MANAGEMENT_ENABLED=false
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: kibana-jenkins
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
  
    # Filebeat - Latest image
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.6.0
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/etc/filebeat/filebeat.yml
    depends_on:
      - logstash

volumes:
  mysql-data:
  es_data:

networks:
  app-network:
    driver: bridge
