services:
  flask-app:
    image: python:3.9
    container_name: flask-app-jenkins
    ports:
      - "5001:5001"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root123
      - MYSQL_DB=blog
    volumes:
      - .:/app
      - ./filebeat.yml:/etc/filebeat/filebeat.yml 
    command: >
      bash -c "
        echo "deb https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-8.x.list &&
        apt update -y &&
        apt install apt-transport-https filebeat -y &&
        systemctl enable filebeat &&
        pip install --upgrade pip && 
        pip install --no-cache-dir -r requirements.txt &&
        python appWithDatabaseAndDoc.py"
    working_dir: /app
    depends_on:
      - mysql
      - logstash

  mysql:
    image: mysql:8.0
    container_name: mysql-jenkins
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=blog
    volumes:
      - mysql-data:/var/lib/mysql
  
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch-jenkins
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
    volumes:
      - es_data:/usr/share/elasticsearch/data
  
  logstash:
    image: logstash
    container_name: logstash-jenkins
    ports:
      - "5044:5044"
    environment:
      - LS_JAVA_OPTS="-Xmx256m -Xms256m"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
  
  kibana:
    image: kibana
    container_name: kibana-jenkins
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=https://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  mysql-data:
  es_data:

networks:
  app-network:
    driver: bridge
