services:
  flask-app:
    image: python:3.9
    container_name: flask-app-jenkins
    ports:
      - "5001:5001"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root123
      - MYSQL_DB=blog
    volumes:
      - .:/app 
    command: >
      bash -c "
        apt update -y &&
        pip install --upgrade pip && 
        pip install --no-cache-dir -r requirements.txt && 
        python appWithDatabaseAndDoc.py"
    working_dir: /app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-jenkins
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=blog
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
